(* This PEG grammar recognizes the limited syntax used when bootstrapping.
   The builtin parser reads tokenized input, so whitespace is implied. *)

START = RULE+ $ ;

RULE = T_IDENTIFIER '=' EXPR ';' ;

EXPR        = EXPR_AND { '|' EXPR_AND } ;
EXPR_AND    = EXPR_CLAUSE+ ; 
EXPR_CLAUSE = T_IDENTIFIER | T_STRING | T_EOF_SYMBOL | T_NIL_SYMBOL ;

T_EOF_SYMBOL  = '$' ;
T_IDENTIFIER  = /[a-zA-Z]\w*/ ;
T_NIL_SYMBOL  = '-' ;
T_STRING      = /'([^\\']|\\.)*'|"([^\\"]|\\.)*"/ ;
